---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/revista1/public_html/joaquinestrada.com.ar/
    - /bin/cp -Rf . $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/.git
    - /bin/rm -f $DEPLOYPATH/.cpanel.yml
    - /bin/rm -f $DEPLOYPATH/README.md
